version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run:
          name: clean-cache
          command: rm -rf node_modules
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: npm run test
      - run:
          name: code-coverage
          command: bash <(curl -s https://codecov.io/bash)
